export const bibleBooksKJV = [
  { name: "Genesis", abbreviations: ["gen"] },
  { name: "Exodus", abbreviations: ["ex"] },
  { name: "Leviticus", abbreviations: ["lev"] },
  { name: "Numbers", abbreviations: ["num"] },
  { name: "Deuteronomy", abbreviations: ["deut"] },
  { name: "Joshua", abbreviations: ["josh"] },
  { name: "Judges", abbreviations: ["judg"] },
  { name: "Ruth", abbreviations: ["ruth"] },
  { name: "1 Samuel", abbreviations: ["1 sam"] },
  { name: "2 Samuel", abbreviations: ["2 sam"] },
  { name: "1 Kings", abbreviations: ["1 kgs"] },
  { name: "2 Kings", abbreviations: ["2 kgs"] },
  { name: "1 Chronicles", abbreviations: ["1 chr"] },
  { name: "2 Chronicles", abbreviations: ["2 chr"] },
  { name: "Ezra", abbreviations: ["ezra"] },
  { name: "Nehemiah", abbreviations: ["neh"] },
  { name: "Esther", abbreviations: ["esth"] },
  { name: "Job", abbreviations: ["job"] },
  { name: "Psalms", abbreviations: ["ps", "psa"] },
  { name: "Proverbs", abbreviations: ["prov"] },
  { name: "Ecclesiastes", abbreviations: ["eccl", "ecc"] },
  { name: "Song of Solomon", abbreviations: ["song", "sol"] },
  { name: "Isaiah", abbreviations: ["isa"] },
  { name: "Jeremiah", abbreviations: ["jer"] },
  { name: "Lamentations", abbreviations: ["lam"] },
  { name: "Ezekiel", abbreviations: ["ezek"] },
  { name: "Daniel", abbreviations: ["dan"] },
  { name: "Hosea", abbreviations: ["hos"] },
  { name: "Joel", abbreviations: ["joel"] },
  { name: "Amos", abbreviations: ["amos"] },
  { name: "Obadiah", abbreviations: ["obad"] },
  { name: "Jonah", abbreviations: ["jonah"] },
  { name: "Micah", abbreviations: ["mic"] },
  { name: "Nahum", abbreviations: ["nah"] },
  { name: "Habakkuk", abbreviations: ["hab"] },
  { name: "Zephaniah", abbreviations: ["zeph"] },
  { name: "Haggai", abbreviations: ["hag"] },
  { name: "Zechariah", abbreviations: ["zech"] },
  { name: "Malachi", abbreviations: ["mal"] },
  { name: "Matthew", abbreviations: ["matt", "mt"] },
  { name: "Mark", abbreviations: ["mk", "mrk"] },
  { name: "Luke", abbreviations: ["lk"] },
  { name: "John", abbreviations: ["jn"] },
  { name: "Acts", abbreviations: ["acts"] },
  { name: "Romans", abbreviations: ["rom"] },
  { name: "1 Corinthians", abbreviations: ["1 cor"] },
  { name: "2 Corinthians", abbreviations: ["2 cor"] },
  { name: "Galatians", abbreviations: ["gal"] },
  { name: "Ephesians", abbreviations: ["eph"] },
  { name: "Philippians", abbreviations: ["phil"] },
  { name: "Colossians", abbreviations: ["col"] },
  { name: "1 Thessalonians", abbreviations: ["1 thess"] },
  { name: "2 Thessalonians", abbreviations: ["2 thess"] },
  { name: "1 Timothy", abbreviations: ["1 tim"] },
  { name: "2 Timothy", abbreviations: ["2 tim"] },
  { name: "Titus", abbreviations: ["titus"] },
  { name: "Philemon", abbreviations: ["philem"] },
  { name: "Hebrews", abbreviations: ["heb"] },
  { name: "James", abbreviations: ["jas"] },
  { name: "1 Peter", abbreviations: ["1 pet"] },
  { name: "2 Peter", abbreviations: ["2 pet"] },
  { name: "1 John", abbreviations: ["1 jn"] },
  { name: "2 John", abbreviations: ["2 jn"] },
  { name: "3 John", abbreviations: ["3 jn"] },
  { name: "Jude", abbreviations: ["jude"] },
  { name: "Revelation", abbreviations: ["rev"] }
] as const;